on:
  push:
    branches: master

name: website

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.7.3' 
 
      - name: Install Chrome (only on macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew cask install google-chrome
 
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: "3.6.3"

      - name: Query dependencies
        run: |
          install.packages("remotes")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-3.6.3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-3.6.3-

      - name: Install packages
        run: remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Build site
        run: rmarkdown::render_site(encoding = "UTF-8")
        shell: Rscript {0}
        
      - name: Build pdf
        run: Rscript ./_build_pdf.R
      
      - uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site/

  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: build
   steps:
     - name: Checkout
       uses: actions/checkout@master
       
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _site # optional
         # Destination path
         path: _site # optional
         
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@master
       env:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GH_TOKEN: ${{ secrets.GHPAT }} # https://github.com/settings/tokens
          BUILD_DIR: _site/                     # "_site/" by default
